import { ADMIN_PASSWORD_HASH } from "./firebase-config.js";
import { addEntries, addEntry, createRound, finishSpin, getRound, hashText, isRoundAdmin, removeEntry, reorderEntry, resetRound, startSpin, updateEntry, updateRound, watchEntries, watchHistory, watchPresence, watchRound } from "./round-service.js";
import { readPublishedSheet, readSpreadsheet, valuesForColumn } from "./import-service.js";
import { drawWheel, spinWheel } from "./wheel.js";

const $ = (selector) => document.querySelector(selector);
let currentRound; let entries = []; let imported; let spinStarted = ""; let finishTimer;
const wheel = $("#adminWheel");
$("#loginForm").addEventListener("submit", async (event) => { event.preventDefault(); if (await hashText($("#adminPassword").value) !== ADMIN_PASSWORD_HASH) { $("#loginMessage").textContent = "La contraseña no es correcta."; $("#loginMessage").dataset.tone = "error"; return; } sessionStorage.setItem("ronda-control-access", "true"); showAdmin(); });
$("#logoutButton").addEventListener("click", () => { sessionStorage.removeItem("ronda-control-access"); location.reload(); });
if (sessionStorage.getItem("ronda-control-access")) showAdmin();
function showAdmin() { $("#adminLogin").classList.add("is-hidden"); $("#adminApp").classList.remove("is-hidden"); const existing = sessionStorage.getItem("ronda-current-admin"); if (existing) loadRound(existing); }
$("#createRoundForm").addEventListener("submit", async (event) => { event.preventDefault(); const title = $("#roundTitle").value.trim(); if (!title) return; const button = event.submitter; button.disabled = true; try { const code = await createRound({ title, removeWinner: $("#removeWinner").checked }); sessionStorage.setItem("ronda-current-admin", code); await loadRound(code); } catch (error) { $("#createMessage").textContent = error.message || "No pudimos crear la ronda."; $("#createMessage").dataset.tone = "error"; } finally { button.disabled = false; } });
$("#newRoundButton").addEventListener("click", () => { sessionStorage.removeItem("ronda-current-admin"); currentRound = null; $("#roundDashboard").classList.add("is-hidden"); $("#roundSetup").classList.remove("is-hidden"); });
async function loadRound(code) { const found = await getRound(code); if (!found || !await isRoundAdmin(found)) { sessionStorage.removeItem("ronda-current-admin"); $("#createMessage").textContent = "Esta sesión ya no tiene acceso administrativo a esa ronda."; return; } currentRound = found; $("#roundSetup").classList.add("is-hidden"); $("#roundDashboard").classList.remove("is-hidden"); $("#roundCodeDisplay").textContent = code; $("#dashboardTitle").textContent = found.title; $("#durationSelect").value = found.durationMs || 7000; $("#soundToggle").checked = Boolean(found.sound); $("#confettiToggle").checked = found.confetti !== false; watchRound(code, handleRound, connectionError); watchEntries(code, renderEntries, connectionError); watchPresence(code, renderPresence, connectionError); watchHistory(code, renderHistory, connectionError); }
function handleRound(round) { if (!round) return; currentRound = round; $("#dashboardTitle").textContent = round.title; $("#roundState").textContent = stateLabel(round.status); $("#spinButton").disabled = round.status === "SPINNING"; $("#stageHint").textContent = hintFor(round.status); if (round.status === "SPINNING" && round.spin && spinStarted !== `${round.spin.spinNumber}-spinning`) { spinStarted = `${round.spin.spinNumber}-spinning`; spinWheel(wheel, round.spin, finishAfterSpin); } if (round.status === "FINISHED" && round.winner && spinStarted !== `${round.winner.spinNumber}-finished`) { spinStarted = `${round.winner.spinNumber}-finished`; showWinner(round.winner, round.confetti); } }
function renderEntries(list) { entries = list; const active = entries.filter((entry) => entry.enabled); drawWheel(wheel, active); $("#wheelCount").textContent = active.length; $("#entryCount").textContent = entries.length; $("#entryList").innerHTML = entries.map((entry, index) => `<li class="entry-row ${entry.enabled ? "" : "disabled"}"><button class="entry-enable" data-action="toggle" data-id="${entry.id}" title="${entry.enabled ? "Desactivar" : "Activar"}" aria-label="${entry.enabled ? "Desactivar" : "Activar"}"></button><span>${escapeHtml(entry.name)}</span><div><button data-action="up" data-index="${index}" class="entry-action" title="Subir">↑</button><button data-action="down" data-index="${index}" class="entry-action" title="Bajar">↓</button><button data-action="edit" data-id="${entry.id}" class="entry-action" title="Editar">✎</button><button data-action="delete" data-id="${entry.id}" class="entry-action delete" title="Eliminar">×</button></div></li>`).join("") || `<li class="empty-list">Aún no hay opciones.</li>`; }
function renderPresence(list) { const fresh = list.filter((person) => !person.lastSeen?.toMillis || Date.now() - person.lastSeen.toMillis() < 70000); $("#presenceCount").textContent = fresh.length; $("#presenceList").innerHTML = fresh.map((person) => `<li><span></span>${escapeHtml(person.name)}</li>`).join("") || `<li class="empty-list">Todavía no hay participantes.</li>`; }
function renderHistory(list) { $("#historyList").innerHTML = list.map((winner) => `<li><span>🏆</span><div><strong>${escapeHtml(winner.winnerName)}</strong><small>Giro #${winner.spinNumber}${winner.createdAt ? ` · ${winner.createdAt.toDate().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : ""}</small></div></li>`).join("") || `<li class="empty-list">Los ganadores aparecerán aquí.</li>`; }
$("#addEntryForm").addEventListener("submit", async (event) => { event.preventDefault(); await addEntry(currentRound.code, $("#entryName").value, entries.length); $("#entryName").value = ""; });
$("#entryList").addEventListener("click", async (event) => { const button = event.target.closest("button[data-action]"); if (!button) return; const entry = entries.find((item) => item.id === button.dataset.id); if (button.dataset.action === "toggle") await updateEntry(currentRound.code, entry.id, { enabled: !entry.enabled }); if (button.dataset.action === "delete" && confirm(`¿Eliminar a ${entry.name}?`)) await removeEntry(currentRound.code, entry.id); if (button.dataset.action === "edit") { const name = prompt("Nombre de la opción", entry.name); if (name?.trim()) await updateEntry(currentRound.code, entry.id, { name: name.trim().slice(0, 100) }); } if (["up", "down"].includes(button.dataset.action)) await reorderEntry(currentRound.code, entries, Number(button.dataset.index), button.dataset.action === "up" ? -1 : 1); });
$("#bulkOpenButton").addEventListener("click", () => $("#bulkDialog").showModal());
$("#bulkConfirmButton").addEventListener("click", async (event) => { event.preventDefault(); const names = $("#bulkText").value.split(/\r?\n/).map((name) => name.trim()).filter(Boolean); if (names.length) await addEntries(currentRound.code, names, entries.length); $("#bulkText").value = ""; $("#bulkDialog").close(); });
$("#excelFile").addEventListener("change", async (event) => { const file = event.target.files[0]; if (!file) return; try { imported = await readSpreadsheet(file); openImportDialog(); } catch (error) { $("#spinMessage").textContent = error.message; $("#spinMessage").dataset.tone = "error"; } finally { event.target.value = ""; } });
function openImportDialog() { const select = $("#importColumn"); select.innerHTML = imported.columns.map((column, index) => `<option value="${index}">${escapeHtml(column)}</option>`).join(""); select.onchange = renderImportPreview; renderImportPreview(); $("#importDialog").showModal(); }
function renderImportPreview() { const values = valuesForColumn(imported, Number($("#importColumn").value)); $("#importSummary").textContent = `Se encontraron ${values.length} registros en la columna seleccionada.`; $("#importPreview").innerHTML = values.slice(0, 12).map((value) => `<span>${escapeHtml(value)}</span>`).join(""); $("#importConfirmButton").textContent = `Importar ${values.length} registros`; }
$("#importConfirmButton").addEventListener("click", async (event) => { event.preventDefault(); await addEntries(currentRound.code, valuesForColumn(imported, Number($("#importColumn").value)), entries.length); $("#importDialog").close(); });
$("#sheetsOpenButton").addEventListener("click", () => $("#sheetsDialog").showModal());
$("#sheetPreviewButton").addEventListener("click", async (event) => { event.preventDefault(); try { imported = await readPublishedSheet($("#sheetUrl").value.trim()); $("#sheetsDialog").close(); openImportDialog(); } catch (error) { $("#sheetMessage").textContent = error.message; $("#sheetMessage").dataset.tone = "error"; } });
$("#spinButton").addEventListener("click", async () => { try { $("#spinMessage").textContent = "Preparando el giro para toda la sala..."; const spin = await startSpin(currentRound, entries); spinStarted = `${spin.spinNumber}-spinning`; spinWheel(wheel, spin, finishAfterSpin); } catch (error) { $("#spinMessage").textContent = error.message; $("#spinMessage").dataset.tone = "error"; } });
function finishAfterSpin() { clearTimeout(finishTimer); finishTimer = setTimeout(async () => { const fresh = await getRound(currentRound.code); if (fresh?.status === "SPINNING") await finishSpin(fresh); }, 180); }
$("#resetRoundButton").addEventListener("click", async () => { if (confirm("¿Reiniciar el estado de la ronda? La lista de opciones se conserva.")) await resetRound(currentRound.code); });
$("#durationSelect").addEventListener("change", (event) => updateRound(currentRound.code, { durationMs: Number(event.target.value) })); $("#soundToggle").addEventListener("change", (event) => updateRound(currentRound.code, { sound: event.target.checked })); $("#confettiToggle").addEventListener("change", (event) => updateRound(currentRound.code, { confetti: event.target.checked }));
$("#copyCodeButton").addEventListener("click", () => copyText(currentRound.code)); $("#copyLinkButton").addEventListener("click", () => copyText(`${location.origin}${location.pathname.replace(/admin\.html$/, "")}room.html?code=${currentRound.code}`)); $("#closeWinnerButton").addEventListener("click", () => $("#winnerOverlay").classList.add("is-hidden"));
function showWinner(winner, confetti) { $("#winnerName").textContent = winner.winnerName; $("#winnerDetail").textContent = `Giro #${winner.spinNumber}`; $("#winnerOverlay").classList.remove("is-hidden"); if (confetti) sprinkle($("#confettiLayer")); }
function sprinkle(layer) { layer.innerHTML = Array.from({ length: 45 }, (_, index) => `<i style="--x:${(index * 37) % 100}%;--d:${.7 + (index % 8) / 10}s;--r:${index * 29}deg"></i>`).join(""); }
function copyText(text) { navigator.clipboard.writeText(text).then(() => { $("#spinMessage").textContent = "Copiado al portapapeles."; }); }
function stateLabel(status) { return ({ WAITING: "ESPERANDO", READY: "LISTA", SPINNING: "GIRANDO", FINISHED: "FINALIZADA" })[status] || status; } function hintFor(status) { return ({ WAITING: "Configura las opciones para comenzar.", SPINNING: "Todos ven el mismo giro.", FINISHED: "Puedes volver a girar o reiniciar la ronda." })[status] || "La ronda está lista."; } function connectionError() { $("#connectionStatus").textContent = "Reconectando"; $("#connectionStatus").dataset.status = "offline"; } function escapeHtml(value) { const div = document.createElement("div"); div.textContent = value; return div.innerHTML; }
