import { getRound, joinPresence, watchEntries, watchPresence, watchRound } from "./round-service.js";
import { drawWheel, spinWheel } from "./wheel.js";

const code = new URLSearchParams(location.search).get("code")?.toUpperCase();
const joinView = document.querySelector("#joinRoomView"); const roomView = document.querySelector("#roomView"); const title = document.querySelector("#joinRoundTitle"); const joinForm = document.querySelector("#roomJoinForm"); const joinMessage = document.querySelector("#roomJoinMessage"); const wheel = document.querySelector("#roomWheel");
let round; let entries = []; let spinId = ""; let leavePresence;
if (!code) location.replace("index.html");
getRound(code).then((found) => { if (!found || found.status === "CLOSED") { title.textContent = "Esta ronda no está disponible"; joinForm.classList.add("is-hidden"); return; } round = found; title.textContent = found.title; }).catch(() => { title.textContent = "No pudimos cargar la ronda"; });
joinForm.addEventListener("submit", async (event) => { event.preventDefault(); const name = document.querySelector("#guestName").value.trim(); if (!name) return; try { leavePresence = await joinPresence(code, name); joinView.classList.add("is-hidden"); roomView.classList.remove("is-hidden"); startRoom(); } catch { joinMessage.textContent = "No pudimos entrar. Revisa tu conexión e inténtalo de nuevo."; joinMessage.dataset.tone = "error"; } });
function startRoom() { document.querySelector("#roomCode").textContent = code; watchEntries(code, (list) => { entries = list; drawWheel(wheel, entries.filter((entry) => entry.enabled)); document.querySelector("#roomWheelCount").textContent = entries.filter((entry) => entry.enabled).length; }); watchPresence(code, renderPresence); watchRound(code, handleRound, connectionError); }
function handleRound(next) { if (!next) return; round = next; document.querySelector("#roomTitle").textContent = round.title; const text = round.status === "SPINNING" ? "La ruleta está girando..." : round.status === "FINISHED" ? "Tenemos un ganador." : "Esperando a que el administrador inicie la ronda..."; document.querySelector("#roomStatus").textContent = text; if (round.status === "SPINNING" && round.spin && spinId !== `${round.spin.spinNumber}-spinning`) { spinId = `${round.spin.spinNumber}-spinning`; spinWheel(wheel, round.spin); } if (round.status === "FINISHED" && round.winner && spinId !== `${round.winner.spinNumber}-finished`) { spinId = `${round.winner.spinNumber}-finished`; showWinner(round.winner, round.confetti); } }
function renderPresence(list) { const fresh = list.filter((person) => !person.lastSeen?.toMillis || Date.now() - person.lastSeen.toMillis() < 70000); document.querySelector("#connectedCount").textContent = `${fresh.length} participante${fresh.length === 1 ? "" : "s"} conectado${fresh.length === 1 ? "" : "s"}`; document.querySelector("#roomPresenceList").innerHTML = fresh.slice(0, 8).map((person) => `<li><span></span>${escapeHtml(person.name)}</li>`).join(""); }
function showWinner(winner, confetti) { document.querySelector("#roomWinnerName").textContent = winner.winnerName; document.querySelector("#roomWinnerDetail").textContent = `Giro #${winner.spinNumber}`; const overlay = document.querySelector("#roomWinnerOverlay"); overlay.classList.remove("is-hidden"); if (confetti) sprinkle(document.querySelector("#roomConfettiLayer")); }
document.querySelector("#roomCloseWinner").addEventListener("click", () => document.querySelector("#roomWinnerOverlay").classList.add("is-hidden"));
function sprinkle(layer) { layer.innerHTML = Array.from({ length: 45 }, (_, i) => `<i style="--x:${(i * 37) % 100}%;--d:${.7 + (i % 8) / 10}s;--r:${i * 29}deg"></i>`).join(""); }
function escapeHtml(value) { const div = document.createElement("div"); div.textContent = value; return div.innerHTML; }
function connectionError() { document.querySelector("#roomStatus").textContent = "Reconectando..."; }
window.addEventListener("beforeunload", () => leavePresence?.());
